### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by NelsonUpenn** [WarrenWeckesser/ufunclab#3]
Very sorry, but newbie would like advice on how to install argfirst. I have Anaconda Python 3.8.1 on my system running macOS13.1 on Apple M1 Pro.
I went to ufunclab on github, downloaded all, and and ran
$ python setup.py --help
That suggested to me that I try
$ python setup.py build
$ python setup.py install
This did not seem to generate any ufunclab.py, so when I later tried
$ python ufunclab/tests/test_first.py
I got ModuleNotFoundError: No module named 'ufunclab'
Can you offer a hint? Thank you.

**Comment by WarrenWeckesser** [comment]
No need to apologize!  I need to work on ensuring that the build system works on the popular platforms.  On my Linux machine, I use `pip install .` in the top directory of the project, but I still haven't worked out what goes wrong when I build on Mac machines.  You can see that the github test suite is failing to build the project on these machines.  Apparently there is problem with the compiler flags that are used.

Note that in a successful build, there won't be a file called `ufunclab.py`.  There will be a directory installed that contains `__init__.py` and many compiled extension modules.

**Comment by NelsonUpenn** [comment]
Many thanks for your immediate reply. This is not urgent for me, so I will watch this thread. If it's helpful, the screenshot below shows that I got ufunclib-main/build/lib.macosx-10.9-x86_64-cpython-38/ufunclab/__init__.py, but I did not find other modules there.
![image](https://user-images.githubusercontent.com/9939124/212554539-082b3761-8d6c-496c-b014-b7c29eb24196.png)

**Comment by WarrenWeckesser** [comment]
@NelsonUpenn, you've probably completely forgotten about this by now, but in case you are interested, I have updated the build system to use meson-python.  There are probably still some kinks to work out, but it works for me locally on a Mac and a Linux workstation, and also on the Mac and Linux jobs in the github CI test suite.  Let me know if you have a chance to try it.

**Comment by NelsonUpenn** [comment]
Wonderful, thank you for letting me know. Phil Nelson

**Comment by WarrenWeckesser** [comment]
I'm closing this issue.  If anyone has trouble building ufunclab from source, open a new issue.
