### ISSUE TITLE
Replace use of numpy.distutils

### ISSUE THREAD

**Issue by WarrenWeckesser** [WarrenWeckesser/ufunclab#4]
`numpy.distutils` is deprecated, so the build process will have to be updated soon.

**Comment by WarrenWeckesser** [comment]
@mjclarke94, I don't have a concrete timeline for this.  I'm currently experimenting with updating the build system to use meson.  Then I'll look into `cibuildwheel` for building wheels for different platforms.

**Comment by mjclarke94** [comment]
Just setting setuptools as the build backend in a pyproject.toml (with a few tweaks for version discovery etc) seemed to get this working as a short term measure if that's of any interest.

**Comment by WarrenWeckesser** [comment]
I have updated the build system to use meson-python.

I'm new to meson-python, so I have probably done some things inefficiently or even incorrectly. It works for me locally on a Mac and a Linux workstation, and all my CI jobs are now passing, but I haven't tried building on Windows (but I hadn't built on Windows previously, either).  If anyone sees a way to imrove the build system, let me know.

@mjclarke94, if you are still using ufunclab, I would be interested to know if the updated build system is helpful for you.
