### ISSUE TITLE
Non-existence numpy.float128 and numpy.complex256 attributes

### ISSUE THREAD

**Issue by ezpzbz** [WarrenWeckesser/ufunclab#5]
[context]
Importing `ufunclab` in an isolated environment with `numpy 1.24.3` fails due to non-existence `numpy.float128` and `numpy.complex256`.

[solution]
Changing those attributes to `numpy.longdouble` and `numpy.longcomplex`, respectively.
For our use-case, I have done it [here](https://github.com/WarrenWeckesser/ufunclab/compare/main...pzarabadip:ufunclab:np_fix) and this seems working.
If this would be an acceptable solution, I'd be glad to open a PR.

**Comment by WarrenWeckesser** [comment]
@ezpzbz, a belated "thanks!" for suggesting this change.  I just cherry-picked your commit from your fork and merged it into the main development branch.  Sorry for not responding much sooner.
